const DISPLAY_SIZE = 300;
const VIDEO_WIDTH = 1080;
const VIDEO_HEIGHT = 1920;

const Y_MIN_VISIBLE = (VIDEO_HEIGHT - VIDEO_WIDTH) / 2 / VIDEO_HEIGHT;
const Y_MAX_VISIBLE = 1 - Y_MIN_VISIBLE;
const VISIBLE_HEIGHT_RATIO = Y_MAX_VISIBLE - Y_MIN_VISIBLE;

export { DISPLAY_SIZE, VIDEO_WIDTH, VIDEO_HEIGHT, Y_MIN_VISIBLE, Y_MAX_VISIBLE, VISIBLE_HEIGHT_RATIO }